### ISSUE TITLE
missing GO terms in GAF file

### ISSUE THREAD

**Issue by iamjli** [tanghaibao/goatools#85] opened 2017-07-11 21:23 UTC
Hi, 

@dvklopfenstein and I had a conversation in issue #79 about discrepancies in GAF files between goa_human.gaf.gz found on the [Gene Ontology site](http://geneontology.org/gene-associations/), and the one used for Enrichr. 

I looked into using GOrilla instead, and they seem to have a much more complete set of GO enrichments than the one taken from Gene Ontology site. For instance, none of my top 3 GO terms found on GOrilla exist: "GO:0010604", "GO:0048522", "GO:0009893". 

I'm using your suggested code to load the GAF file: 

```
from goatools.associations import read_gaf

# Import GO annotations from http://geneontology.org/gene-associations/goa_human.gaf.gz
goatools_annotations = read_gaf("../data/goa_human.gaf")
```

Any ideas where I can find the most complete annotation file that is human specific? 

Thanks,
Johnny

**Comment by dvklopfenstein** [comment] 2017-07-16 07:53
The GO terms you list have hundreds or thousands of GO terms child terms underneath them:

  * GO:0048522 positive regulation of cellular process
  * GO:0009893 positive regulation of metabolic process
  * GO:0010604 positive regulation of macromolecule metabolic process

There are over 2,400 child GO terms for the 3 GO terms that you list. 
Of those 2,400+ child GO terms, ~1,200 GO terms are in the human association in goa_human.gaf.

Some examples of more specific GO terms that are both found in the human annotation and are children to  __"GO:0010604 positive regulation of macromolecule metabolic process"__ in your list include:

  * GO:0046016 positive regulation of transcription by glucose
  * GO:1903518 positive regulation of single strand break repair
  * GO:0048295 positive regulation of isotype switching to IgE isotypes

Often, the more specific child terms like the ones found in the second bullet list are preferable results from a GO enrichment analyses than the GO terms found in the first bullet list. So you may prefer using the associations in goa_human.gaf. I would hesitate to say the lack of these extremely broad terms that you list means that the goa_human.gaf is less complete.

Regardless, GOATOOLS is not the source for gene-GO annotations, so the better people to talk to regarding the content of associations is the providers of the associations. The gene ontology consortium help may be able to point you where to go for questions on the human annotation. Their link is https://github.com/geneontology/helpdesk/issues

Thank you for your interest in GOATOOLS and your interesting questions. It was interesting to look into the details of the associations for those GO IDs.

I am going to close this issue. If you feel that the issue is not answered, please feel free to open a new issue.

**Closed by dvklopfenstein** 2017-07-16 07:53 UTC
