### ISSUE TITLE
Generating association file

### ISSUE THREAD

**Issue by ougadougou** [tanghaibao/goatools#65] opened 2016-06-11 07:23 UTC
Hi,

I am trying to run GO term enrichment analysis with my own background set for humans, mice, and yeast. I am assuming that I could use "find_enrichment.py" and include a text file for my query genes (or proteins) and a background set, correct? However, I am curious as to how I could generate an association file. Have you used any UniProt database to generate the association file?

Any help is appreciated.

Thanks

Rav

**Comment by dvklopfenstein** [comment] 2016-06-11 18:55
I can look into UniProt. Which type of ids are you using for your set of
study items and your set of population items?

NCBI GeneID? (An integer)
or
Ensembl gene id? (ENSG...)

Can you include example files with your study genes and population genes so
that we may test it if we decide to add a UniProt interface?

No promises, but we will take a look if you provide us with some example
files.

**Comment by ougadougou** [comment] 2016-06-13 03:35
Thank you for the prompt response.  Here's an example list of UNIPROTIDs (P04264
P08670, P13647, P35908, P02538, Q7z794, P19013, P05787). I was wondering if there is a way to get the gene names from here so that I could match that with the genes listed in the associations file. I'd assume that I have to use another program to convert UniprotIDs to Gene Names. 

Also, I have noticed that the associations file lists all the GO IDs related to a gene name. However, is there a way to only list the "Molecular function" ontologies or "Biological Process" ontologies. I am particularly interested if a certain group of genes have an enrichment for just the molecular function ontologies or biological process ontologies.

Sincerely thank you for your help

**Comment by dvklopfenstein** [comment] 2016-06-13 11:32
UniProtIDs-to-GeneIDs for human (hsa) are available in the file,
*uniprot_sprot_hsa_AC2nt.py*, in
https://github.com/dvklopfenstein/biocode/tree/master/pydvkbiology/dnld

The uniprot_sprot_hsa_AC2nt.py, file contains a dictionary of UniProt IDs -
to - Entrez GeneIDs. This file is generated from a download from UniProt
completed in March 2016.

For annotations used in gene ontology analysis in my own research, I use
NCBI's gene2go file found at ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/. The
gene2go file contains an Entrez GeneID and its associated GO term IDs.

So using *uniprot_sprot_hsa_AC2nt.py *and NCBI's *gene2go*, you can get the
GO annotations from UniProt IDs.

If this works for you, I can look into adding Mouse and Yeast. I am a
doctoral candidate and one of my research projects involves Mouse, so it
should not be a big deal to add Mouse. Yeast should be okay too. Please let
me know if adding UniProtID2EntrezID files for yeast and mouse would be
helpful to you.

**Comment by ougadougou** [comment] 2016-06-13 18:37
Your code is very helpful. It would be great if you can please add mouse and yeast also as I would need those for my work. 

Also, would you please tell me if the p-value that is generated in your code has the same meaning as the definition of the p-value from hypergeometric distribution. By that, this is how the p-value is defined:

" To actually generate a p-value, rather than a simple probability, instead of asking the question, what is the probability of having 5 out of 10 genes with this annotation, given that 42 out 6000 have it, we ask the question what is the probability of having 5 or more out of 10 genes having this annotation. The p-value is defined as the chance of seeing your observation, or better, given the background distribution.  We calculate this by summing our probabilities for 5 out of 10, 6 out of 10, 7 out of 10 etc. "

**Comment by dvklopfenstein** [comment] 2016-06-13 21:23
Yes. the p-value is generated using the hypergeometric distribution because
Fisher's Exact test uses the hypergeometric distribution. And the function
we use to create uncorrected p-values is Fisher's Exact Test.

From http://asq.org/pub/sixsigma/past/vol2_issue4/bower.html:

"Fisher's Exact test is exact because it uses the exact hypergeometric
distribution rather than the approximate chi-square distribution to compute
the p-value."

**Comment by dvklopfenstein** [comment] 2016-06-14 14:04
Do you want a particular strain of yeast?  There are:

7,909 entries in UniProt for "Saccharomyces cerevisiae"
     15 different strains of "Saccharomyces cerevisiae" in UniProt

Here are the counts for the different strains in UniProt:

     42 Saccharomyces cerevisiae (Baker's yeast).
   6721 Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's
yeast).
    118 Saccharomyces cerevisiae (strain AWRI1631) (Baker's yeast).
     21 Saccharomyces cerevisiae (strain AWRI796) (Baker's yeast).
      2 Saccharomyces cerevisiae (strain CEN.PK113-7D) (Baker's yeast).
     17 Saccharomyces cerevisiae (strain FostersB) (Baker's yeast).
     19 Saccharomyces cerevisiae (strain FostersO) (Baker's yeast).
    143 Saccharomyces cerevisiae (strain JAY291) (Baker's yeast).
      2 Saccharomyces cerevisiae (strain Kyokai no. 7 / NBRC 101557)
(Baker's
    148 Saccharomyces cerevisiae (strain Lalvin EC1118 / Prise de mousse)
     18 Saccharomyces cerevisiae (strain Lalvin QA23) (Baker's yeast).
    199 Saccharomyces cerevisiae (strain RM11-1a) (Baker's yeast).
     19 Saccharomyces cerevisiae (strain VIN 13) (Baker's yeast).
    414 Saccharomyces cerevisiae (strain YJM789) (Baker's yeast).
     21 Saccharomyces cerevisiae (strain Zymaflore VL3) (Baker's yeast).
      1 Saccharomyces cerevisiae killer virus M1 (ScV-M1) (Saccharomyces
      2 Saccharomyces cerevisiae virus L-A (ScV-L-A) (ScVL1).
      2 Saccharomyces cerevisiae virus L-BC (ScV-L-BC) (ScVLa).

**Comment by ougadougou** [comment] 2016-06-14 14:51
Ideally, I'd like BY4741 strain as I am working on that.. But I am not sure how much of a difference there would be between genomes of different strains, Thank you

**Comment by ougadougou** [comment] 2016-07-03 17:05
Hey, I was wondering if you have gotten a chance to work on UniprotID2EntrezID files for mouse and yeast. Really appreciate your help. Thank you

**Comment by dvklopfenstein** [comment] 2016-07-06 00:59
Hello, Please use at your own risk. I am not currently working on Yeast. But here is what I have done:

ANY yeast (Saccharomyces cerevisiae) in uniprot_sprot.dat downloaded from:
ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete

is included in Python dictionaries in:
https://github.com/dvklopfenstein/biocode/blob/master/pydvkbiology/dnld/uniprot_sprot_sce_AC2nt.py
https://github.com/dvklopfenstein/biocode/blob/master/pydvkbiology/dnld/uniprot_sprot_sce_GeneID2ACs.py

This includes 5,910 NCBI GeneIDs and 13,394 UniProt proteins.

This includes all these yeast proteins found in uniprot_sprot.dat:

  # Counts of proteins per strain in UniProt June 2016:
  #
  #    42 Saccharomyces cerevisiae (Baker's yeast).
  #  6721 Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast).
  #   118 Saccharomyces cerevisiae (strain AWRI1631) (Baker's yeast).
  #    21 Saccharomyces cerevisiae (strain AWRI796) (Baker's yeast).
  #     2 Saccharomyces cerevisiae (strain CEN.PK113-7D) (Baker's yeast).
  #    17 Saccharomyces cerevisiae (strain FostersB) (Baker's yeast).
  #    19 Saccharomyces cerevisiae (strain FostersO) (Baker's yeast).
  #   143 Saccharomyces cerevisiae (strain JAY291) (Baker's yeast).
  #     2 Saccharomyces cerevisiae (strain Kyokai no. 7 / NBRC 101557) (Baker's
  #   148 Saccharomyces cerevisiae (strain Lalvin EC1118 / Prise de mousse)
  #    18 Saccharomyces cerevisiae (strain Lalvin QA23) (Baker's yeast).
  #   199 Saccharomyces cerevisiae (strain RM11-1a) (Baker's yeast).
  #    19 Saccharomyces cerevisiae (strain VIN 13) (Baker's yeast).
  #   414 Saccharomyces cerevisiae (strain YJM789) (Baker's yeast).
  #    21 Saccharomyces cerevisiae (strain Zymaflore VL3) (Baker's yeast).
  #     1 Saccharomyces cerevisiae killer virus M1 (ScV-M1) (Saccharomyces
  #     2 Saccharomyces cerevisiae virus L-A (ScV-L-A) (ScVL1).
  #     2 Saccharomyces cerevisiae virus L-BC (ScV-L-BC) (ScVLa).

I hope it is helpful, but this is all I can do right now...

**Comment by ougadougou** [comment] 2016-08-10 22:54
Hello, I have two questions regarding the GOEA object. 
First, I am looking at significant GO terms for a group of proteins and some of those proteins are linked to the same gene. So, I am trying to understand how GOEA analysis works in that situation. For instance, if I'm interested in identifying significant GO terms in 6 proteins that belong to the same gene name, then they would all the same entrez gene ID. When I use those 6 proteins (based on entrez gene ID) for GOEA analysis with a background set, I notice that my results summary file generates values of 1/7 for "ratio in study

**Comment by ougadougou** [comment] 2016-08-10 23:16
Sorry...couldn't complete my previous question....
The results file generates values of 1/6 for "ratio in study" instead of "6/6" although all the proteins belong to the same gene. Is this something that you have encountered?

My second question is: how could I list out just the top significant GO terms rather than getting a list of all the GO terms. I have noticed that the results report generates all the BP, CC, and MF results and then I had to manually filter them for significant GO terms based on "ratio in study" and depth. Please note that I am already selecting for fdr_bh p-values of less than 0.05. I'm only interested in GO terms that are significant in all of my study genes. I notice that the report generates significant GO terms for not only all the study genes, but for all ranges of them. By that I mean, if there are 6 genes in my study group, it list GO terms that are significant in 6/6, 5/6, 4/6, 3/6, 2/6, 1/6, and 0/6 (when I am interested in GO terms that are significant in all 6).  Your help is highly appreciated. Thanks

**Comment by dvklopfenstein** [comment] 2017-07-02 03:06
Thank you for your interest in GOATOOLS and taking the time to contact us.

If you want to list all top significant GO terms that are selected for all of your study genes, you would do something like this seen similar to code in the test, https://github.com/tanghaibao/goatools/blob/master/tests/test_nbt3102_goea_subset.py:

```
    goeaobj = get_goeaobj("fdr_bh", geneids_pop, taxid)
    goea_results_all = goeaobj.run_study(geneids_study)
    goea_results_sig = [r for r in goea_results_all if r.p_fdr_bh < 0.05]
    goea_results_sub = [r for r in goea_results_sig if r.study_count > r.study_n]
    goeaobj.wr_xlsx("nbt3102_geneids.xlsx", goea_results_sub)
```

The line that is most relevant to your question is:

 **goea_results_sub = [r for r in goea_results_sig if r.study_count > r.study_n]**

I am going to close this issue. If you do not feel the issue is closed, please feel free t re-open it. Thank you again for your interest in GOATOOLS and taking the time to open to alert us to your specific requirements.

**Closed by dvklopfenstein** 2017-07-02 03:06 UTC
