### ISSUE TITLE
error  when running python scripts/plot_go_term.py --term=GO:####### --gml

### ISSUE THREAD

**Issue by r1-12king** [tanghaibao/goatools#100] opened 2018-05-14 12:59 UTC
Hello author, I am a student. I have encountered some problems and I hope to get your help.

when I running "python scripts/plot_go_term.py --term=GO:0008135 --gml", it report an error, 
 "AttributeError: module 'networkx' has no attribute 'from_pydot'",I found a reason on *https://stackoverflow.com/questions/35279733/what-could-cause-networkx-pygraphviz-to-work-fine-alone-but-not-together*

but,when I change “nx.from_pydot(grph)”（lines600）to "nx.drawing.nx_pydot.from_pydot(grph)",a new error  have emerged，The following is the error message

################################
Traceback (most recent call last):
  File "scripts\plot_go_term.py", line 60, in <module>
    draw_children=opts.draw_children)
  File "scripts\..\goatools\obo_parser.py", line 605, in draw_lineage
    nx.write_gml(self.label_wrap, gmlfile)
  File "<decorator-gen-200>", line 2, in write_gml
  File "D:\development\Anaconda3\lib\site-packages\networkx\utils\decorators.py", line 220, in _open_file
    result = func(*new_args, **kwargs)
  File "D:\development\Anaconda3\lib\site-packages\networkx\readwrite\gml.py", line 717, in write_gml
    for line in generate_gml(G, stringizer):
  File "D:\development\Anaconda3\lib\site-packages\networkx\readwrite\gml.py", line 626, in generate_gml
    multigraph = G.is_multigraph()
AttributeError: 'function' object has no attribute 'is_multigraph'
################################

I can't solve this problem,so I hope get you help.
thanks！

**Comment by dvklopfenstein** [comment] 2018-05-14 22:46
@tanghaibao, would you mind looking at this? I did not do the networkx code and have other issues to attend to.

**Comment by tanghaibao** [comment] 2021-05-23 03:55
I could not reproduce this error and don't own a Windows to test this. Since this issue has been around for a long while, closing this NTBF for now. Please feel free to re-open for anyone running into this as well.

**Closed by tanghaibao** 2021-05-23 03:55 UTC
