### ISSUE TITLE
Significant p value returned for GO term with no genes in study

### ISSUE THREAD

**Issue by gaberosser** [tanghaibao/goatools#122] opened 2019-03-07 12:33 UTC
I've run GOEA for my (human) genes of interest, following the steps in the tutorial (code below). I used the study and BG gene lists in the attached file `study_and_bg_genes.xlsx`. The ontologies and associations were downloaded using the provided functions. The full results are in the attached `go_results.xlsx`. 

I noticed in the results that some pathways are showing up as significant (by Bonferroni), despite having no matching genes in the study. For example, `GO:0004984` and `GO:1903231`. There may be more.

Is this a bug, or I have I misunderstood the results output?

```
    # load data
    study_genes = ...
    bg_genes = ...

    # load ontologies
    obo_fn = base.download_go_basic_obo()
    obodag = obo_parser.GODag(obo_fn)

    # load associations
    genetogo_fn = base.download_ncbi_associations()
    geneid2gos_hu = associations.read_ncbi_gene2go(genetogo_fn, taxids=[9606])

    print("{N:,} annotated human genes".format(N=len(geneid2gos_hu)))

    goe_obj = go_enrichment.GOEnrichmentStudy(
        bg_genes,
        geneid2gos_hu,
        obodag,
    )
    goea_res = goe_obj.run_study(study_genes)
    goe_obj.wr_xlsx('go_results.xlsx', goea_res)

```

[go_results.xlsx](https://github.com/tanghaibao/goatools/files/2941200/go_results.xlsx)
[study_and_bg_genes.xlsx](https://github.com/tanghaibao/goatools/files/2941204/study_and_bg_genes.xlsx)

**Comment by gaberosser** [comment] 2019-03-07 12:34
Oh sorry, I forgot the relevant library import statements: `from goatools import base, obo_parser, associations, go_enrichment`

**Comment by dvklopfenstein** [comment] 2019-03-07 21:03
@gaberosser ,

Thank you for your interest in GOATOOLS and for taking the time to write us.

Those terms are purified, rather than enriched. This means that it is statistically significant that these terms are missing from the result. They are marked with a 'p' rather than an 'e' in the enrichment column, column C.

This is working as intended. I did write a new test to be sure that terms with 0 study terms that are found significant are reported as purified, not enriched for an extra sanity check. The test passes. So all seems well.

I will close this issue. If you feel it is closed in error, please feel free to open a new issue. Thank you again for your interest in GOATOOLS and good question.

**Closed by dvklopfenstein** 2019-03-07 21:03 UTC

**Comment by gaberosser** [comment] 2019-03-08 06:13
Oh, OK! Thank you very much for the prompt clarification. I was wondering about the interpretation of 'purified' but had failed to find much documentation about it. I probably missed it - apologies!

Thanks for providing a very useful set of tools.

**Comment by dvklopfenstein** [comment] 2019-03-10 22:28
@gaberosser,

You make a good point that this could be confusing.

To more clearly show enriched/purified, I added the counts of enriched/purified results in the runtime messages. Also, the default sort of the results will now sort enriched/purified first instead of second so all purified results will be presented together.

```
       5 GO terms found significant (< 0.05=alpha) (  5 enriched +   0 purified): local bonferroni
       5 GO terms found significant (< 0.05=alpha) (  5 enriched +   0 purified): local sidak
       5 GO terms found significant (< 0.05=alpha) (  5 enriched +   0 purified): local holm
      17 GO terms found significant (< 0.05=alpha) ( 16 enriched +   1 purified): statsmodels fdr_bh
```
