### ISSUE TITLE
using "ND" entries in the GAF file.

### ISSUE THREAD

**Issue by illxi** [tanghaibao/goatools#75] opened 2017-03-23 10:55 UTC
It seems like goatools automatically ignore the entries with evidence code "ND" in the GAF file. But for my case I actually needed to use them. I found in the associations.py line 132, `if 'NOT' not in ntgaf.Qualifier and evidence_code != 'ND':`, this seems to be hardcore. It would be very helpful in the future version, if there is an option to include these entries.

**Comment by dvklopfenstein** [comment] 2017-03-31 13:08
I will look at this shortly...

**Comment by dvklopfenstein** [comment] 2017-03-31 13:10
We will add support for ND entries if the user specifies that they want it.
It will be in the code in a couple days.

**Comment by dvklopfenstein** [comment] 2017-04-10 23:46
The modifications are in. Please do a pull to be sure it does what you need. Report back if you need something different. 

To read a GAF file while allowing GO terms with **ND** Evidence codes using the new keyword argument, **keep_ND**:

```
# Read associations for human
read_gaf("goa_human.gaf", keep_ND=True)

# Read associations for mouse
read_gaf("gene_association.mgi", keep_ND=True)

# Read associations for fly
read_gaf("gene_association.fb", keep_ND=True)
```

Examples of how read a GAF, while allowing ND Evidence codes are also in [tests/test_read_gaf_allow_nd.py](https://github.com/tanghaibao/goatools/blob/master/tests/test_read_gaf_allow_nd.py)

**Comment by dvklopfenstein** [comment] 2017-05-26 19:50
Thank you for your interest in GOATOOLS and taking the time to contact us. We are closing this issue for now as we have not heard back and are hoping that the issue is resolved. If it is not resolved or if you have future questions, please feel free to open a new issue. Thank you for your time and interest in GOATOOLS.

**Closed by dvklopfenstein** 2017-05-26 19:50 UTC

**Comment by datduong** [comment] 2019-06-24 01:42
Is possible to read all GO terms not just BP ? For example, in the read_gaf, there is a `namespace="BP"`, is possible to have an option namespace="all" ? Thanks.

**Comment by dvklopfenstein** [comment] 2019-06-24 15:42
This is a great request. Can you open a new issue?

We can read all namespaces, as you would like to do, but it would be a good idea to make accessing this functionality more user-friendly.

**Comment by datduong** [comment] 2019-06-24 21:18
I just did that. Thanks.
