### ISSUE TITLE
import from genes_NCBI_10090_ProteinCoding results in unresolved reference

### ISSUE THREAD

**Issue by RewatiAtGit** [tanghaibao/goatools#161] opened 2020-04-11 08:45 UTC
the import 
from goatools.test_data.genes_NCBI_10090_ProteinCoding import GENEID2NT as GeneID2nt_mus gives an error saying "GENEID2NT" is an unresolved reference. This is true for human genes as well.

**Comment by dvklopfenstein** [comment] 2020-06-19 18:09
Thank you so much for your interest in GOATOOLS and taking the time to write us.

I am currently updating this section of GOATOOLs and will take a look.

**Comment by dvklopfenstein** [comment] 2020-06-20 22:14
I am not sure what might be wrong. Below is what I did, which was successful. Maybe your GOATOOLs version might need to be updated?

Please note also, that I just added a [**new Jupyter notebook**](https://github.com/tanghaibao/goatools/blob/master/notebooks/backround_genes_ncbi.ipynb) showing how to download the latest population gene sets from NCBI Gene. The test data is old and is meant to used only for tests.

```
$ python3
Python 3.6.9 (default, Jul 21 2019, 14:33:59)
[GCC 7.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from goatools.test_data.genes_NCBI_10090_ProteinCoding import GENEID2NT as GeneID2nt_mus
>>> print(len(GeneID2nt_mus))
28212
```

**Comment by tanghaibao** [comment] 2021-05-23 21:04
I also could not reproduce this error either with the recent `goatools` version (the latest at this time is `v1.1.5`).
Closing issue for now and feel free to re-open if this problem persists after upgrade (`pip install -U goatools`).

**Closed by tanghaibao** 2021-05-23 21:04 UTC
